class_name SFXData extends Resource

enum Type{
	NONE = 1000, 
	VANGUARD_REACT = 501, 
	VANGUARD_FIRING = 0, 
	VANGUARD_IMPACT = 1, 
	SENTINEL_REACT = 502, 
	SENTINEL_FIRING = 2, 
	SENTINEL_IMPACT = 3, 
	CRYO_REACT = 503, 
	CRYO_FIRING = 4, 
	CRYO_IMPACT = 5, 
	LANCER_REACT = 504, 
	LANCER_FIRING = 6, 
	LANCER_IMPACT = 7, 
	HEATER_REACT = 505, 
	HEATER_FIRING = 8, 
	OVERWATCH_REACT = 506, 
	OVERWATCH_FIRING = 9, 
	SURGE_REACT = 507, 
	SURGE_FIRING = 10, 
	TREMOR_REACT = 508, 
	TREMOR_IMPACT = 11, 
	CRUSHER_REACT = 509, 
	CRUSHER_FIRING = 12, 
	BLOCKADE_REACT = 510, 
	BLOCKADE_BUILD = 13, 
	REFINERY_REACT = 511, 
	REFINERY_FIRING = 14, 
	IONIZER_REACT = 512, 
	IONIZER_FIRING = 15, 
	REFINERY_GENERATE = 16, 
	REFINERY_LUCKY_STRIKE = 17, 
	OVERWATCH_ORBITAL_STRIKE_FIRING = 18, 
	OVERWATCH_ORBITAL_STRIKE_IMPACT = 19, 
	OVERWATCH_ORBITAL_STRIKE_CHIME = 20, 
	BLOCKADE_EXPLOSION = 21, 
	BLOCKADE_HIT = 22, 
	POLY_REACT = 513, 
	COMMANDER_HIT = 23, 
	MECHANIC_IMPACT = 24, 
	RESEARCHER_IMPACT = 25, 
	PATHFINDER_FIRING = 26, 
	PATHFINDER_FIRING_SIEGE = 27, 
	SURVEYOR_FIRING = 28, 


	UI_BUTTON_ENTERED = 101, 
	UI_BUTTON_CLICKED = 102, 
	UI_DIALOGUE_BLIP = 103, 
	UI_PLUCK = 104, 
	UI_SWITCH = 105, 
	UI_TECH_POINT_ASSIGNED = 106, 
	UI_TECH_POINT_RESET = 107, 
	UI_MITOSIS_BONUS = 108, 
	UI_MARKET_OPEN = 109, 
	UI_MARKET_CLOSED = 110, 
	UI_SIMPLE_BLIP_1 = 111, 
	UI_SIMPLE_BLIP_2 = 112, 
	UI_SIMPLE_BLIP_3 = 113, 
	UI_ARTIFACT_SELECT = 114, 


	ERROR_ONE = 202, 

	TOWER_SUMMON_IMPACT = 401, 
	TOWER_SUMMON_FALL = 402, 
	SUMMONING_SOUND = 403, 
	COMMANDER_TELEPORT_IN = 404, 
	TOWER_LEVEL_UP = 405, 
	TOWER_SALVAGED = 406, 
	EXCAVATE_LASER = 407, 
	EXCAVATE_CRUMBLE = 408, 
	TOWER_SUMMON_CONFIRM = 409, 
	TOWER_HEXED = 410, 
	COMMANDER_ENERGY_GAIN = 411, 
	WAVE_ORE_REWARD = 412, 

	DPS_GOLD_PING = 413, 
	DPS_SILVER_PING = 414, 
	DPS_BRONZE_PING = 415, 

	SHOP_OPEN = 416, 
	BUFF_APPLIED = 417, 
	NIGHT_SIREN = 418, 
	ENERGY_SHIELD_BREAK = 419, 

	AUGMENT_SKILL = 420, 
	POWER_SURGE_SKILL = 421, 
	SUMMON_POLY_SKILL = 422, 

	RADAR_SCAN = 423, 
	RADAR_TELEPORT_IN = 424, 
	RADAR_TELEPORT_OUT = 425, 

	TELEPORT_ENEMY_SKILL = 426, 

	RESEARCH_SKILL = 427, 
	RESEARCH_SKILL_EUREKA = 428, 
	OVERCLOCK_SKILL = 429, 
	ACCELERATE_SKILL = 430, 
	TOXIC_FIELD_SKILL = 431, 
	PATHFINDER_FLOW_STATE_ENTER = 432, 
	PATHFINDER_FLOW_STATE_EXIT = 433, 
	PATHFINDER_SIEGE_MODE = 434, 
	PATHFINDER_SNIPE = 435, 
	PATHFINDER_GRAVITY_SKILL_INTRO = 436, 
	PATHFINDER_GRAVITY_SKILL_OUTRO = 437, 
	TOWER_HOVER_VALID = 438, 
	TOWER_HOVER_INVALID = 439, 
	SURVEYOR_TERRAFORM = 440, 
	PROSPECT_SKILL = 441, 
}

@export_range(0, 10) var limit: int = 5
@export var type: Type
@export var sound_effect: AudioStream
@export_range(-40, 20) var volume = 0
@export_range(0.0, 4.0, 0.01) var pitch_scale = 1.0
@export_range(0.0, 1.0, 0.01) var pitch_randomness = 0.0

var audio_count = 0

func change_audio_count(amount: int):
	audio_count = max(0, audio_count + amount)

func has_open_limit() -> bool:
	return audio_count < limit

func on_audio_finished():
	change_audio_count(-1)
